// Code generated by executioncell/gen; DO NOT EDIT.
// Run "go generate ./executioncell" to regenerate.

package executioncell

const (
	ContractSchemaSHA256 = "91aaca7bd56d43d825b7b57cc4cf15fcf30423df15d9e16153acf457b8f964cc"
	FixtureSuiteSHA256   = "4d58fc29f3397627b3f663773ee77d62ffb4eb298928c952ac5623a6b016518d"
)
