// Code generated by executioncell/gen; DO NOT EDIT.
// Run "go generate ./executioncell" to regenerate.

package executioncell

const (
	ContractSchemaSHA256 = "61d275fc84a3c06b49e1d5a0ed72ce89afc986fb63d88697961dfa2bf61e5d80"
	FixtureSuiteSHA256   = "cbf2f9c487500730ff523afd99a9ba33d750580e4b47a51f03324dc43fedeefd"
)
