// Code generated by matrix/gen; DO NOT EDIT.
// Run `make generate` (go generate ./matrix/...) to regenerate.

package matrix

import "github.com/RenseiAI/donmai/agent"

// LegacyAliasMap maps each back-compat ProviderName to its canonical
// (harness, endpoint, host) cell. Introduced in P1 but NOT YET consumed —
// buildAgentRunRegistry (donmai) and the rensei-tui fork keep routing by
// ProviderName until P1b swaps them to this map. Generated from the
// hand-authored validCells' legacyProviderId anchors.
var LegacyAliasMap = map[agent.ProviderName]CellKey{
	"agy-cli":  {Harness: "antigravity", Endpoint: "google", Host: "oauth-cli"},
	"amp":      {Harness: "amp", Endpoint: "anthropic", Host: "direct"},
	"claude":   {Harness: "claude-code", Endpoint: "anthropic", Host: "oauth-cli"},
	"codex":    {Harness: "codex", Endpoint: "openai", Host: "oauth-cli"},
	"gemini":   {Harness: "raw", Endpoint: "google", Host: "direct"},
	"ollama":   {Harness: "raw", Endpoint: "local", Host: "local"},
	"opencode": {Harness: "opencode", Endpoint: "openai", Host: "direct"},
	"pi":       {Harness: "pi", Endpoint: "anthropic", Host: "direct"},
	"stub":     {Harness: "stub", Endpoint: "stub", Host: "local"},
}
