package matrix

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
)

// Artifact filenames (committed at the matrix/ package root, NOT under
// testdata/ — testdata/ is excluded from go build and platform/rensei-tui
// must be able to read these files).
const (
	FileCapabilityMatrix = "capability-matrix.json"
	FileHarnesses        = "harnesses.json"
	FileEndpoints        = "endpoints.json"
	FileMatrix           = "matrix.json"
	FileRegistryGen      = "registry_gen.go"
)

// Artifacts is the rendered byte content for every generated file, keyed by
// filename. Deterministic: the same Built always renders byte-identical output
// (sorted everywhere; no timestamps).
type Artifacts struct {
	Files map[string][]byte
}

// Render marshals a Built into the four JSON artifacts + the registry_gen.go Go
// source. JSON is indented 2-space with a trailing newline (gofmt/editor
// friendly and stable). The registry source is the legacy-alias map only (the
// P1b ctor list is out of scope for P1).
func (b *Built) Render() (*Artifacts, error) {
	capabilityMatrix, err := marshalJSON(b.Matrix)
	if err != nil {
		return nil, fmt.Errorf("marshal capability-matrix: %w", err)
	}

	harnessesDoc := struct {
		SchemaVersion string       `json:"schemaVersion"`
		ContractABI   string       `json:"contractAbi"`
		GeneratedFrom string       `json:"generatedFrom"`
		Harnesses     []HarnessRow `json:"harnesses"`
	}{SchemaVersion, ContractABI, GeneratedFrom, b.Harnesses}
	harnesses, err := marshalJSON(harnessesDoc)
	if err != nil {
		return nil, fmt.Errorf("marshal harnesses: %w", err)
	}

	endpointsDoc := struct {
		SchemaVersion string        `json:"schemaVersion"`
		ContractABI   string        `json:"contractAbi"`
		GeneratedFrom string        `json:"generatedFrom"`
		Endpoints     []EndpointRow `json:"endpoints"`
	}{SchemaVersion, ContractABI, GeneratedFrom, b.Endpoints}
	endpoints, err := marshalJSON(endpointsDoc)
	if err != nil {
		return nil, fmt.Errorf("marshal endpoints: %w", err)
	}

	// matrix.json carries the cells + denylist + legacy aliases (the
	// runtime-routing-relevant slice of the full document).
	matrixDoc := struct {
		SchemaVersion string                `json:"schemaVersion"`
		ContractABI   string                `json:"contractAbi"`
		GeneratedFrom string                `json:"generatedFrom"`
		Cells         []HarnessEndpointCell `json:"cells"`
		Denylist      []CellKey             `json:"denylist"`
		LegacyAliases []LegacyAlias         `json:"legacyAliases"`
	}{SchemaVersion, ContractABI, GeneratedFrom, b.Matrix.Cells, b.Matrix.Denylist, b.AliasMap}
	matrixJSON, err := marshalJSON(matrixDoc)
	if err != nil {
		return nil, fmt.Errorf("marshal matrix: %w", err)
	}

	registry, err := renderRegistry(b.AliasMap)
	if err != nil {
		return nil, fmt.Errorf("render registry: %w", err)
	}

	return &Artifacts{Files: map[string][]byte{
		FileCapabilityMatrix: capabilityMatrix,
		FileHarnesses:        harnesses,
		FileEndpoints:        endpoints,
		FileMatrix:           matrixJSON,
		FileRegistryGen:      registry,
	}}, nil
}

// marshalJSON produces deterministic 2-space-indented JSON with a trailing
// newline and HTML escaping disabled (so URLs in baseUrlTmpl read cleanly and
// stay byte-stable).
func marshalJSON(v any) ([]byte, error) {
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	enc.SetIndent("", "  ")
	if err := enc.Encode(v); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// renderRegistry emits registry_gen.go: the legacy ProviderName → CellKey map
// as Go source for the runner (P1b consumes it; introduced-but-not-consumed in
// P1). Deterministic order (aliases are pre-sorted by ProviderName). The
// output is run through go/format so it is gofmt/gofumpt-stable — `make fmt`
// and `make lint` leave it untouched.
func renderRegistry(aliases []LegacyAlias) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by matrix/gen; DO NOT EDIT.\n")
	buf.WriteString("// Run `make generate` (go generate ./matrix/...) to regenerate.\n\n")
	buf.WriteString("package matrix\n\n")
	buf.WriteString("import \"github.com/RenseiAI/donmai/agent\"\n\n")
	buf.WriteString("// LegacyAliasMap maps each back-compat ProviderName to its canonical\n")
	buf.WriteString("// (harness, endpoint, host) cell. Introduced in P1 but NOT YET consumed —\n")
	buf.WriteString("// buildAgentRunRegistry (donmai) and the rensei-tui fork keep routing by\n")
	buf.WriteString("// ProviderName until P1b swaps them to this map. Generated from the\n")
	buf.WriteString("// hand-authored validCells' legacyProviderId anchors.\n")
	buf.WriteString("var LegacyAliasMap = map[agent.ProviderName]CellKey{\n")
	for _, a := range aliases {
		buf.WriteString(fmt.Sprintf(
			"\t%q: {Harness: %q, Endpoint: %q, Host: %q},\n",
			string(a.ProviderName), string(a.Cell.Harness), string(a.Cell.Endpoint), string(a.Cell.Host),
		))
	}
	buf.WriteString("}\n")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("gofmt registry source: %w", err)
	}
	return formatted, nil
}
