package matrix

import (
	"fmt"
	"sort"
	"strings"

	"github.com/RenseiAI/donmai/agent"
)

// This file renders the generated harness support page (matrix/SUPPORT.md):
// one row per harness and session mode, with the OSS columns, all derived
// from the live harness manifests, the hand-authored cells (stability/smoked
// evidence), and the hand-authored binary pins. It publishes what the code
// already declares; it never invents enforcement or eligibility.
//
// Column derivations (each traces to exactly one declaration):
//   - launch lane: the session mode itself (autonomous=headless,
//     human_controlled=interactive).
//   - model delivery: the mode's prompt profile UserDelivery values.
//   - effort: the harness Caps.SupportsReasoningEffort flag.
//   - tool delivery: the mode's tool/lifecycle NativeToolPolicyDelivery +
//     PermissionConfigDelivery values.
//   - mcp delivery: the mode's tool/lifecycle MCPDelivery values.
//   - extension delivery: the mode's tool/lifecycle ToolPluginDelivery values.
//   - exec tool/network deny: the generated per-mode deny-baseline records
//     (workspace-write grant at index 0 via RenderExecutionSecurity).
//   - resume: the harness Caps.SupportsSessionResume flag.
//   - events: the mode's lifecycle delivery, fidelity, and event count.
//   - attach: the harness Caps.SupportsInteractivePTY flag.
//   - evidence tier / production eligible: the mode's tool/lifecycle profile
//     fields.
//   - binary pin: the hand-authored harnessBinaryPins PinnedVersion ("-" when
//     the harness ships no external binary).
//   - stability / smoked: aggregates over the hand-authored validCells for
//     the harness ("-" stability when the harness anchors no cell).
//
// A mode that declares several tool/lifecycle profiles (codex interactive
// today) joins the per-profile values with " / " after sorting unique.

// RenderSupportPage renders the deterministic SUPPORT.md content for built.
// Rows sort by harness name, then mode. Output ends with exactly one trailing
// newline and contains no timestamps, so the parity test can byte-compare it.
func RenderSupportPage(built *Built) string {
	var buf strings.Builder
	buf.WriteString("<!-- Code generated by matrix/gen; DO NOT EDIT.\n")
	buf.WriteString("     Run `make generate` (go generate ./matrix/...) to regenerate. -->\n\n")
	buf.WriteString("# Harness support\n\n")
	buf.WriteString("One row per harness and session mode, generated from the harness\n")
	buf.WriteString("manifests, the hand-authored cells (stability/smoked), and the\n")
	buf.WriteString("hand-authored binary pins. A hand edit here fails the parity gate;\n")
	buf.WriteString("a code change without regeneration fails it too.\n\n")
	buf.WriteString("| harness | mode | launch lanes | model delivery | effort | tool delivery | mcp delivery | extension delivery | exec tool deny | exec network deny | resume | events | attach | evidence tier | prod eligible | binary pin | stability | smoked |\n")
	buf.WriteString("| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |\n")

	byName := map[agent.HarnessName]HarnessRow{}
	for _, h := range built.Harnesses {
		byName[h.Name] = h
	}
	pins := map[agent.HarnessName]HarnessBinaryPin{}
	for _, p := range built.Matrix.BinaryPins {
		pins[p.Harness] = p.HarnessBinaryPin
	}

	type rowKey struct {
		harness agent.HarnessName
		mode    agent.PromptSessionMode
	}
	var keys []rowKey
	for _, h := range built.Harnesses {
		for _, mode := range supportModes(h) {
			keys = append(keys, rowKey{harness: h.Name, mode: mode})
		}
	}
	sort.Slice(keys, func(i, j int) bool {
		if keys[i].harness != keys[j].harness {
			return keys[i].harness < keys[j].harness
		}
		return keys[i].mode < keys[j].mode
	})

	for _, k := range keys {
		h := byName[k.harness]
		buf.WriteString("| " + strings.Join([]string{
			escapeCell(string(h.Name)),
			escapeCell(string(k.mode)),
			escapeCell(launchLanes(k.mode)),
			escapeCell(joinSorted(promptUserDeliveries(h, k.mode))),
			escapeCell(boolCell(h.Caps.SupportsReasoningEffort)),
			escapeCell(joinSorted(toolDeliveries(h, k.mode))),
			escapeCell(joinSorted(mcpDeliveries(h, k.mode))),
			escapeCell(joinSorted(extensionDeliveries(h, k.mode))),
			escapeCell(execToolDeny(h, k.mode)),
			escapeCell(execNetworkDeny(h, k.mode)),
			escapeCell(boolCell(h.Caps.SupportsSessionResume)),
			escapeCell(joinSorted(eventCells(h, k.mode))),
			escapeCell(boolCell(h.Caps.SupportsInteractivePTY)),
			escapeCell(joinSorted(evidenceTiers(h, k.mode))),
			escapeCell(prodEligibleCell(h, k.mode)),
			escapeCell(binaryPinCell(pins, h.Name)),
			escapeCell(stabilityCell(built, h.Name)),
			escapeCell(smokedCell(built, h.Name)),
		}, " | ") + " |\n")
	}
	return buf.String()
}

// supportModes is the mode set for one harness row: the union of the prompt
// and tool/lifecycle profile modes, matching harnessExecutionSecurityRows.
func supportModes(h HarnessRow) []agent.PromptSessionMode {
	seen := map[agent.PromptSessionMode]bool{}
	var modes []agent.PromptSessionMode
	for _, profile := range h.PromptDelivery {
		if !seen[profile.Mode] {
			seen[profile.Mode] = true
			modes = append(modes, profile.Mode)
		}
	}
	for _, profile := range h.ToolLifecycle {
		if !seen[profile.Mode] {
			seen[profile.Mode] = true
			modes = append(modes, profile.Mode)
		}
	}
	sort.Slice(modes, func(i, j int) bool { return modes[i] < modes[j] })
	return modes
}

// toolProfiles returns the tool/lifecycle profiles for one harness and mode,
// sorted by profile ID for deterministic joins.
func toolProfiles(h HarnessRow, mode agent.PromptSessionMode) []agent.ToolLifecycleProfile {
	var out []agent.ToolLifecycleProfile
	for _, profile := range h.ToolLifecycle {
		if profile.Mode == mode {
			out = append(out, profile)
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].ID < out[j].ID })
	return out
}

func launchLanes(mode agent.PromptSessionMode) string {
	if mode == agent.PromptModeHumanControlled {
		return "interactive"
	}
	return "headless"
}

func promptUserDeliveries(h HarnessRow, mode agent.PromptSessionMode) []string {
	var out []string
	for _, profile := range h.PromptDelivery {
		if profile.Mode == mode && string(profile.UserDelivery) != "" {
			out = append(out, string(profile.UserDelivery))
		}
	}
	return out
}

func toolDeliveries(h HarnessRow, mode agent.PromptSessionMode) []string {
	var out []string
	for _, profile := range toolProfiles(h, mode) {
		for _, kind := range []agent.ToolDeliveryKind{profile.NativeToolPolicyDelivery, profile.PermissionConfigDelivery} {
			if string(kind) != "" {
				out = append(out, string(kind))
			}
		}
	}
	return out
}

func mcpDeliveries(h HarnessRow, mode agent.PromptSessionMode) []string {
	var out []string
	for _, profile := range toolProfiles(h, mode) {
		if string(profile.MCPDelivery) != "" {
			out = append(out, string(profile.MCPDelivery))
		}
	}
	return out
}

func extensionDeliveries(h HarnessRow, mode agent.PromptSessionMode) []string {
	var out []string
	for _, profile := range toolProfiles(h, mode) {
		if string(profile.ToolPluginDelivery) != "" {
			out = append(out, string(profile.ToolPluginDelivery))
		}
	}
	return out
}

func execToolDeny(h HarnessRow, mode agent.PromptSessionMode) string {
	for _, row := range h.ExecutionSecurity {
		if row.Mode == mode {
			return string(row.ToolDenyBaseline)
		}
	}
	return "-"
}

func execNetworkDeny(h HarnessRow, mode agent.PromptSessionMode) string {
	for _, row := range h.ExecutionSecurity {
		if row.Mode == mode {
			return string(row.NetworkDenyBaseline)
		}
	}
	return "-"
}

func eventCells(h HarnessRow, mode agent.PromptSessionMode) []string {
	var out []string
	for _, profile := range toolProfiles(h, mode) {
		out = append(out, fmt.Sprintf("%s(%s,%d)", string(profile.LifecycleDelivery), string(profile.LifecycleFidelity), len(profile.LifecycleEvents)))
	}
	return out
}

func evidenceTiers(h HarnessRow, mode agent.PromptSessionMode) []string {
	var out []string
	for _, profile := range toolProfiles(h, mode) {
		if profile.EvidenceTier != "" {
			out = append(out, profile.EvidenceTier)
		}
	}
	return out
}

func prodEligibleCell(h HarnessRow, mode agent.PromptSessionMode) string {
	profiles := toolProfiles(h, mode)
	if len(profiles) == 0 {
		return "-"
	}
	var out []string
	for _, profile := range profiles {
		out = append(out, boolCell(profile.ProductionEligible))
	}
	return joinSorted(out)
}

func binaryPinCell(pins map[agent.HarnessName]HarnessBinaryPin, name agent.HarnessName) string {
	pin, ok := pins[name]
	if !ok || pin.PinnedVersion == "" {
		return "-"
	}
	return pin.PinnedVersion
}

// stabilityCell aggregates the hand-authored cell stabilities for one
// harness: the sorted unique stability values joined with "/". A harness
// with no cell (the bare interactive shell today) reports "-".
func stabilityCell(built *Built, name agent.HarnessName) string {
	seen := map[string]bool{}
	var out []string
	for _, c := range built.Matrix.Cells {
		if c.Harness != name || c.Stability == "" || seen[c.Stability] {
			continue
		}
		seen[c.Stability] = true
		out = append(out, c.Stability)
	}
	if len(out) == 0 {
		return "-"
	}
	sort.Strings(out)
	return strings.Join(out, "/")
}

// smokedCell reports whether any hand-authored cell for the harness proved
// it in a smoke lane.
func smokedCell(built *Built, name agent.HarnessName) string {
	for _, c := range built.Matrix.Cells {
		if c.Harness == name && c.Smoked {
			return "yes"
		}
	}
	return "no"
}

func boolCell(v bool) string {
	if v {
		return "yes"
	}
	return "no"
}

func joinSorted(values []string) string {
	seen := map[string]bool{}
	var out []string
	for _, v := range values {
		if v == "" || seen[v] {
			continue
		}
		seen[v] = true
		out = append(out, v)
	}
	if len(out) == 0 {
		return "-"
	}
	sort.Strings(out)
	return strings.Join(out, " / ")
}

func escapeCell(s string) string {
	return strings.ReplaceAll(s, "|", "\\|")
}
