package daemon

import (
	"log/slog"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// defaultWorkerCommand returns the WorkerCommand the spawner uses when
// the operator has not set one explicitly. The command is `<self-exe>
// agent run` — `os.Executable()` is consulted first so the spawned
// child process is the same binary as the running daemon (correct for
// the launchd / systemd install case where `daemon run` and `agent
// run` ship as a single binary).
//
// Falls back to `donmai agent run` on PATH when os.Executable cannot
// resolve. Returns nil when no resolution path succeeds OR when we
// detect a `go test` binary — the spawner then keeps its `/bin/sh -c
// "exit 0"` fallback. We log a warning at runtime when the stub fires
// in production so operators don't silently lose work.
//
// (F.2.8 — daemon wire-up.)
func defaultWorkerCommand() []string {
	exe, err := os.Executable()
	if err != nil || exe == "" {
		return lookPathFallback()
	}
	// Resolve symlinks so the launched child sees an absolute,
	// non-symlinked path.
	if resolved, rerr := filepath.EvalSymlinks(exe); rerr == nil {
		exe = resolved
	}
	if _, statErr := os.Stat(exe); statErr != nil {
		return lookPathFallback()
	}
	// Test-binary guard: when invoked from `go test`, the executable
	// is the per-package test binary (e.g. daemon.test) which has no
	// `agent run` subcommand. Falling through to PATH would produce
	// the same hang. Detect via the conventional ".test" suffix and
	// the testing.Short flag is unreliable here. Skip the default in
	// this case so tests opt into a stub WorkerCommand explicitly.
	if isGoTestBinary(exe) {
		return nil
	}
	return []string{exe, "agent", "run"}
}

// lookPathFallback locates the worker binary via PATH when os.Executable()
// is unavailable. Resolution order:
//
//  1. "donmai" — the OSS binary name and the preferred resolution target.
//  2. "af"     — legacy back-compat name kept so existing PATH installs
//     (e.g. rensei-tui embeds that were on PATH as "af") continue
//     to work without a forced upgrade.
//
// Returns nil when no binary is found; the spawner then falls through to its
// /bin/sh stub (sessions exit immediately and operators see a log warning).
func lookPathFallback() []string {
	for _, name := range []string{"donmai", "af"} {
		if p, err := exec.LookPath(name); err == nil && p != "" {
			return []string{p, "agent", "run"}
		}
	}
	slog.Warn("daemon: could not resolve donmai binary for WorkerCommand; spawner will use stub fallback (sessions will exit immediately)")
	return nil
}

// isGoTestBinary returns true when the running executable looks like
// a `go test` binary — the per-package test runner `<pkg>.test` or a
// path under TMPDIR generated by the test toolchain.
func isGoTestBinary(exe string) bool {
	base := filepath.Base(exe)
	if strings.HasSuffix(base, ".test") {
		return true
	}
	// `go test -c` and the default test runner emit names like
	// `<pkg>.test` in TMPDIR; the suffix check above covers those.
	// The rare `go test -exec` path uses the original binary name —
	// fall through to false in that case (operators driving that
	// path should set WorkerCommand explicitly).
	return false
}
