package agent

import (
	"bytes"
	"encoding/json"
	"flag"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
)

// updateGolden regenerates the canonical golden fixture(s) from the
// in-code canonical span when set: `go test ./agent/... -run Golden -update`.
var updateGolden = flag.Bool("update", false, "regenerate span golden fixtures in testdata/")

const goldenLlmCallPath = "testdata/llm_call_span.golden.json"

// canonicalLlmCallSpan is the single fully-populated LlmCallSpan that
// pins the wire contract. Every optional field is set so absence of any
// field on the wire is detectable. It is the source of truth for the
// shared golden fixture; the platform mirror copies the generated bytes
// byte-for-byte.
func canonicalLlmCallSpan() LlmCallSpan {
	return LlmCallSpan{
		SpanCore: SpanCore{
			TraceID:           "0af7651916cd43dd8448eb211c80319c",
			SpanID:            "b7ad6b7169203331",
			ParentSpanID:      "b9c7c989f97918e1",
			Kind:              SpanKindLLM,
			Name:              "chat anthropic/claude-opus",
			StartTimeUnixNano: "1719600000000000000",
			EndTimeUnixNano:   "1719600002500000000",
			Status:            SpanStatus{Code: StatusOK},
			Donmai: DonmaiSpanExtensions{
				OrgID:           "org_123",
				WorkspaceID:     "org_123",
				SessionID:       "sess_abc",
				WorkType:        "sdlc",
				PoolID:          "pool_1",
				CedarDecisionID: "dec_9",
				PromptHash:      "sha256:aa",
				ContextHash:     "sha256:bb",
				ModelSnapshotID: "snap_7",
			},
		},
		GenAI: GenAIAttributes{
			System:                    "anthropic",
			RequestModel:              "claude-opus-4",
			UsageInputTokens:          1200,
			UsageOutputTokens:         340,
			UsageCacheReadInputTokens: 800,
			ResponseFinishReason:      "end_turn",
		},
	}
}

// fullSpanCore returns a SpanCore with every field populated, used to
// build fully-populated variants for the lossless round-trip table. The
// caller overrides Kind to the variant's canonical kind.
func fullSpanCore(kind SpanKind) SpanCore {
	return SpanCore{
		TraceID:           "0af7651916cd43dd8448eb211c80319c",
		SpanID:            "b7ad6b7169203331",
		ParentSpanID:      "b9c7c989f97918e1",
		Kind:              kind,
		Name:              "span " + string(kind),
		StartTimeUnixNano: "1719600000000000000",
		EndTimeUnixNano:   "1719600002500000000",
		Status:            SpanStatus{Code: StatusOK, Message: "ok"},
		Donmai: DonmaiSpanExtensions{
			OrgID:           "org_123",
			WorkspaceID:     "org_123",
			SessionID:       "sess_abc",
			WorkType:        "sdlc",
			PoolID:          "pool_1",
			CedarDecisionID: "dec_9",
			PromptHash:      "sha256:aa",
			ContextHash:     "sha256:bb",
			ModelSnapshotID: "snap_7",
		},
	}
}

// TestSpan_AllKindsRoundTrip exercises every Span variant through
// MarshalSpan → UnmarshalSpan, asserting the decoded concrete type
// matches and that no field is lost (normalized JSON deep-equal).
func TestSpan_AllKindsRoundTrip(t *testing.T) {
	t.Parallel()
	cases := []struct {
		name     string
		in       Span
		kind     SpanKind
		wantType string
	}{
		{
			"llm",
			canonicalLlmCallSpan(),
			SpanKindLLM,
			"agent.LlmCallSpan",
		},
		{
			"tool",
			ToolSpan{SpanCore: fullSpanCore(SpanKindTool), ToolName: "Bash", ToolUseID: "tu-1", IsError: true},
			SpanKindTool,
			"agent.ToolSpan",
		},
		{
			"chain",
			ChainSpan{SpanCore: fullSpanCore(SpanKindChain), ChainName: "compose-step"},
			SpanKindChain,
			"agent.ChainSpan",
		},
		{
			"retrieval",
			RetrievalSpan{SpanCore: fullSpanCore(SpanKindRetrieval), QueryHash: "sha256:qq", DocumentCount: 7},
			SpanKindRetrieval,
			"agent.RetrievalSpan",
		},
		{
			"agent",
			AgentSpan{SpanCore: fullSpanCore(SpanKindAgent), AgentProvider: "claude"},
			SpanKindAgent,
			"agent.AgentSpan",
		},
		{
			"subagent",
			SubagentSpan{SpanCore: fullSpanCore(SpanKindSubagent), SubagentProvider: "codex"},
			SpanKindSubagent,
			"agent.SubagentSpan",
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			if tc.in.spanKind() != tc.kind {
				t.Fatalf("spanKind() = %q, want %q", tc.in.spanKind(), tc.kind)
			}

			data, err := MarshalSpan(tc.in)
			if err != nil {
				t.Fatalf("MarshalSpan: %v", err)
			}
			wantKind := `"kind":"` + string(tc.kind) + `"`
			if !strings.Contains(string(data), wantKind) {
				t.Fatalf("wire missing kind discriminator %s\nwire=%s", wantKind, data)
			}

			out, err := UnmarshalSpan(data)
			if err != nil {
				t.Fatalf("UnmarshalSpan: %v", err)
			}
			if gotType := reflect.TypeOf(out).String(); gotType != tc.wantType {
				t.Fatalf("decoded type = %q, want %q", gotType, tc.wantType)
			}
			if out.spanKind() != tc.kind {
				t.Fatalf("decoded spanKind() = %q, want %q", out.spanKind(), tc.kind)
			}

			gotJSON, _ := MarshalSpan(out)
			wantJSON, _ := MarshalSpan(tc.in)
			if !reflect.DeepEqual(normalize(t, gotJSON), normalize(t, wantJSON)) {
				t.Fatalf("variant lost a field on round-trip:\nwant=%s\ngot =%s", wantJSON, gotJSON)
			}
		})
	}
}

// TestSpan_KindWireValues guards each variant's wire "kind" literal and
// that spanKind() returns the matching constant.
func TestSpan_KindWireValues(t *testing.T) {
	t.Parallel()
	cases := []struct {
		in   Span
		want string
	}{
		{LlmCallSpan{SpanCore: SpanCore{Kind: SpanKindLLM}}, "llm"},
		{ToolSpan{SpanCore: SpanCore{Kind: SpanKindTool}}, "tool"},
		{ChainSpan{SpanCore: SpanCore{Kind: SpanKindChain}}, "chain"},
		{RetrievalSpan{SpanCore: SpanCore{Kind: SpanKindRetrieval}}, "retrieval"},
		{AgentSpan{SpanCore: SpanCore{Kind: SpanKindAgent}}, "agent"},
		{SubagentSpan{SpanCore: SpanCore{Kind: SpanKindSubagent}}, "subagent"},
	}
	for _, tc := range cases {
		if got := string(tc.in.spanKind()); got != tc.want {
			t.Errorf("%T.spanKind() = %q, want %q", tc.in, got, tc.want)
		}
		data, err := MarshalSpan(tc.in)
		if err != nil {
			t.Fatalf("%T MarshalSpan: %v", tc.in, err)
		}
		var head struct {
			Kind string `json:"kind"`
		}
		if err := json.Unmarshal(data, &head); err != nil {
			t.Fatalf("%T decode kind: %v", tc.in, err)
		}
		if head.Kind != tc.want {
			t.Errorf("%T wire kind = %q, want %q", tc.in, head.Kind, tc.want)
		}
	}

	// AllSpanKinds / Valid sanity: every listed kind is Valid and the
	// list is exactly the six kinds.
	if got := len(AllSpanKinds()); got != 6 {
		t.Errorf("AllSpanKinds() len = %d, want 6", got)
	}
	for _, k := range AllSpanKinds() {
		if !k.Valid() {
			t.Errorf("AllSpanKinds() contains invalid kind %q", k)
		}
	}
	if SpanKind("alien").Valid() {
		t.Error(`SpanKind("alien").Valid() = true, want false`)
	}
}

// TestSpan_RequiredKeysPresent asserts the canonical LlmCallSpan
// serializes every required top-level and nested wire key.
func TestSpan_RequiredKeysPresent(t *testing.T) {
	t.Parallel()
	data, err := MarshalSpan(canonicalLlmCallSpan())
	if err != nil {
		t.Fatalf("MarshalSpan: %v", err)
	}
	m := normalize(t, data)

	for _, k := range []string{
		"traceId", "spanId", "kind", "name",
		"startTimeUnixNano", "endTimeUnixNano", "status", "donmai", "genAi",
	} {
		if _, ok := m[k]; !ok {
			t.Errorf("top-level wire key %q missing", k)
		}
	}

	// startTimeUnixNano / endTimeUnixNano must be JSON strings (D2).
	if _, ok := m["startTimeUnixNano"].(string); !ok {
		t.Errorf("startTimeUnixNano is %T, want string", m["startTimeUnixNano"])
	}
	if _, ok := m["endTimeUnixNano"].(string); !ok {
		t.Errorf("endTimeUnixNano is %T, want string", m["endTimeUnixNano"])
	}

	donmai, ok := m["donmai"].(map[string]any)
	if !ok {
		t.Fatalf("donmai is %T, want object", m["donmai"])
	}
	for _, k := range []string{"orgId", "workspaceId", "sessionId"} {
		if _, ok := donmai[k]; !ok {
			t.Errorf("donmai.%s missing", k)
		}
	}

	genAi, ok := m["genAi"].(map[string]any)
	if !ok {
		t.Fatalf("genAi is %T, want object", m["genAi"])
	}
	for _, k := range []string{"system", "requestModel", "usageInputTokens", "usageOutputTokens"} {
		if _, ok := genAi[k]; !ok {
			t.Errorf("genAi.%s missing", k)
		}
	}
}

// TestSpan_GoldenMatches pins the canonical LlmCallSpan wire bytes to the
// shared golden fixture. The fixture is the cross-language parity anchor:
// the platform mirror is a byte-identical copy. Run with -update to
// regenerate.
func TestSpan_GoldenMatches(t *testing.T) {
	canonical := canonicalLlmCallSpan()

	want, err := json.MarshalIndent(canonical, "", "  ")
	if err != nil {
		t.Fatalf("MarshalIndent canonical: %v", err)
	}
	want = append(want, '\n')

	if *updateGolden {
		if err := os.MkdirAll(filepath.Dir(goldenLlmCallPath), 0o755); err != nil {
			t.Fatalf("mkdir testdata: %v", err)
		}
		if err := os.WriteFile(goldenLlmCallPath, want, 0o644); err != nil {
			t.Fatalf("write golden: %v", err)
		}
		t.Logf("updated golden fixture %s", goldenLlmCallPath)
	}

	data, err := os.ReadFile(goldenLlmCallPath)
	if err != nil {
		t.Fatalf("read golden (run `go test ./agent/... -run TestSpan_GoldenMatches -update` to create): %v", err)
	}

	if !bytes.Equal(data, want) {
		t.Fatalf("golden fixture out of date; run `go test ./agent/... -run TestSpan_GoldenMatches -update`\nhave:\n%s\nwant:\n%s", data, want)
	}

	// The golden bytes must decode to a span equal to the canonical one.
	sp, err := UnmarshalSpan(data)
	if err != nil {
		t.Fatalf("UnmarshalSpan(golden): %v", err)
	}
	llm, ok := sp.(LlmCallSpan)
	if !ok {
		t.Fatalf("golden decoded to %T, want agent.LlmCallSpan", sp)
	}
	if !reflect.DeepEqual(llm, canonical) {
		t.Fatalf("golden decoded span != canonical\ngolden=%+v\ncanon =%+v", llm, canonical)
	}
}

// TestUnmarshalSpan_ErrorPaths verifies error reporting on bad input.
func TestUnmarshalSpan_ErrorPaths(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name      string
		in        string
		wantSubst string
	}{
		{"invalid-json", `not json`, "decode span kind"},
		{"missing-kind", `{"name":"x"}`, "missing kind discriminator"},
		{"unknown-kind", `{"kind":"alien"}`, `unknown span kind "alien"`},
		{"variant-decode-bad-field", `{"kind":"tool","toolName":12}`, "decode ToolSpan"},
		{"variant-decode-bad-genai", `{"kind":"llm","genAi":{"usageInputTokens":"nope"}}`, "decode LlmCallSpan"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			_, err := UnmarshalSpan([]byte(tt.in))
			if err == nil {
				t.Fatalf("expected error containing %q, got nil", tt.wantSubst)
			}
			if !strings.Contains(err.Error(), tt.wantSubst) {
				t.Fatalf("error %q missing %q", err.Error(), tt.wantSubst)
			}
		})
	}
}

// TestMarshalSpan_NilSpan guards against accidental nil panic.
func TestMarshalSpan_NilSpan(t *testing.T) {
	t.Parallel()
	if _, err := MarshalSpan(nil); err == nil {
		t.Fatal("MarshalSpan(nil) returned nil error")
	}
}
